// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestKuy.Models;

namespace TestKuy.Migrations
{
    [DbContext(typeof(ImageDbContext))]
    partial class ImageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestKuy.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CartId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("imageProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("shippingShipName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("imageProductId");

                    b.HasIndex("shippingShipName");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("TestKuy.Models.ImageModel", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("CartID")
                        .HasColumnType("float");

                    b.Property<double>("CartQuantity")
                        .HasColumnType("float");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProductDetail")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("ProductPrice")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TestKuy.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<float>("OrderTotal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TestKuy.Models.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VGAId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VGAName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VGAimage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.Property<string>("imageProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("shippingShipName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("imageProductId");

                    b.HasIndex("shippingShipName");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TestKuy.Models.Shipping", b =>
                {
                    b.Property<string>("ShipName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ShipCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipPhone")
                        .HasColumnType("int");

                    b.Property<string>("ShipState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ShipZipcode")
                        .HasColumnType("int");

                    b.HasKey("ShipName");

                    b.ToTable("Shippings");
                });

            modelBuilder.Entity("TestKuy.Models.CartItem", b =>
                {
                    b.HasOne("TestKuy.Models.ImageModel", "image")
                        .WithMany()
                        .HasForeignKey("imageProductId");

                    b.HasOne("TestKuy.Models.Shipping", "shipping")
                        .WithMany()
                        .HasForeignKey("shippingShipName");
                });

            modelBuilder.Entity("TestKuy.Models.OrderItem", b =>
                {
                    b.HasOne("TestKuy.Models.Order", "order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("TestKuy.Models.ImageModel", "image")
                        .WithMany()
                        .HasForeignKey("imageProductId");

                    b.HasOne("TestKuy.Models.Shipping", "shipping")
                        .WithMany()
                        .HasForeignKey("shippingShipName");
                });
#pragma warning restore 612, 618
        }
    }
}
